[package]
name = "sparse"
version = "0.1.0"
authors = ["Yomguithereal <guillaumeplique@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
indicatif = "0.16.2"
serde = { version = "1", features = ["derive"] }
sparseset = "1.0.0"
